os: linux
compiler: gcc
dist: xenial
language: rust
rust: 
  - stable
cache: cargo
jobs:
  include:
  - stage: Build
    name: X86-64 Build
    arch: amd64
    script:
    - cargo build  --release
    before_deploy:
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mkdir release
    - mkdir ./release/$TRAVIS_TAG
    - cp ./target/release/server_v2 ./release/$TRAVIS_TAG/server
  
    deploy:
      provider: gcs
      access_key_id: $GCS_ID
      secret_access_key: $GCS_KEY
      bucket: gcode3d
      upload_dir: builds/x86-64/
      local_dir: ./release
      cleanup: false
      edge: true
      acl: public-read

    after_deploy:
      - echo "https://storage.googleapis.com/gcode3d/builds/x86-64/$TRAVIS_TAG/server"

  - 
    arch: arm64
    name: ARM64 Build
    script:
    - cargo build  --release
    before_deploy:
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mkdir release
    - mkdir ./release/$TRAVIS_TAG
    - cp ./target/release/server_v2 ./release/$TRAVIS_TAG/server
    after_deploy:
      - echo "https://storage.googleapis.com/gcode3d/builds/arm64/$TRAVIS_TAG/server"

    deploy:
      provider: gcs
      access_key_id: $GCS_ID
      secret_access_key: $GCS_KEY
      bucket: gcode3d
      upload_dir: builds/arm64/
      local_dir: ./release
      cleanup: false
      edge: true
      acl: public-read

  - 
    arch: arm64
    name: ARM32 Build
    before_install:
    - sudo dpkg --add-architecture armhf
    - sudo apt-get update -yq
    - sudo apt-get install -y libssl-dev:armhf
    - sudo apt-get install -y curl git build-essential
    - sudo apt-get install -y libc6-armhf-cross libc6-dev-armhf-cross gcc-arm-linux-gnueabihf 
    - rustup target add armv7-unknown-linux-gnueabihf

    - cargo install cross
    env:
      - TARGET=armv7-unknown-linux-gnueabihf
      - PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig"
      - PKG_CONFIG_ALLOW_CROSS="true"
    addons:
        apt:
          packages: *armhf
    script:
    - cargo build  --release --target=armv7-unknown-linux-gnueabihf
    before_deploy:
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mkdir release
    - mkdir ./release/$TRAVIS_TAG
    - cp ./target/armv7-unknown-linux-gnueabihf/server_v2 ./release/$TRAVIS_TAG/server
    after_deploy:
      - echo "https://storage.googleapis.com/gcode3d/builds/arm32/$TRAVIS_TAG/server"

    deploy:
      provider: gcs
      access_key_id: $GCS_ID
      secret_access_key: $GCS_KEY
      bucket: gcode3d
      upload_dir: builds/arm32/
      local_dir: ./release
      cleanup: false
      edge: true
      acl: public-read