os: linux
compiler: gcc
dist: xenial
language: rust
rust: 
  - stable
cache: cargo
jobs:
  include:
  - stage: Build
    arch: amd64
    script:
    - cargo build  --release
    before_deploy:
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mkdir release
    - cp ./target/release/server_v2 ./release/build_x86_64
  
    deploy:
      provider: gcs
      access_key_id: $GCS_ID
      secret_access_key: $GCS_KEY
      bucket: gcode3d
      upload_dir: /builds/x86-64/$TRAVIS_TAG
      local_dir: ./release
      cleanup: false
      edge: true

  - 
    arch: arm64
    script:
    - cargo build  --release
    before_deploy:
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mkdir release
    - cp ./target/release/server_v2 ./release/build_arm64
  
    deploy:
      provider: gcs
      access_key_id: $GCS_ID
      secret_access_key: $GCS_KEY
      bucket: gcode3d
      upload_dir: /builds/arm/$TRAVIS_TAG
      local_dir: ./release
      cleanup: false
      edge: true
