os: linux
compiler: gcc
dist: xenial
language: rust
rust: 
  - stable
cache: cargo
jobs:
  include:
  - stage: Build
    arch: amd64
    script:
    - cargo build  --release
  - 
    arch: arm64
    script:
    - cargo build  --release
    before_deploy:
    - git config --local user.name "Gcode 3d"
    - git config --local user.email "tobias.feld@hotmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
  - stage: Deploy
    script: 
    - git config --local user.name "Gcode 3d"
    - git config --local user.email "tobias.feld@hotmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      token: $GHTOKEN
      file: 
        - "./target/release/server_v2.exe"
        - "./target/release/server_v2"
      prerelease: true
      cleanup: false
      skip_cleanup: true


