[package]
name = "server_v2"
version = "0.1.0"
authors = ["Tobias Feld <tobias.feld@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "c028d63e5ba275927424397fe9d67cfebdc138ec" }
uuid = { version = "0.8", features = ["serde", "v4"] }